version: "3.0"
services:
  travel_db:
    container_name: "travel_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_db_data:/var/lib/postgresql/postgresql_db_data:rw
    networks:
      - custom
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - "6379:6379"
    networks:
      - custom

  travel_db_test:
    container_name: "travel_db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge

volumes:
  postgresql_db_data: