"""add track to model place

Revision ID: 95c520d4e900
Revises: 9f659034d50c
Create Date: 2023-01-12 18:24:03.286418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c520d4e900'
down_revision = '9f659034d50c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_places')
    op.add_column('places', sa.Column('track_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'places', 'tracks', ['track_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'track_id')
    op.create_table('track_places',
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name='track_places_place_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name='track_places_track_id_fkey'),
    sa.PrimaryKeyConstraint('track_id', 'place_id', name='track_places_pkey')
    )
    # ### end Alembic commands ###
