"""reformat user model fix

Revision ID: 20d50ce9a0b6
Revises: 6258029475d7
Create Date: 2023-01-14 23:43:47.937582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20d50ce9a0b6'
down_revision = '6258029475d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=postgresql.ENUM(name='role_type'),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=postgresql.ENUM(name='role_type'),
               nullable=True)
    # ### end Alembic commands ###
