"""add new fields user model

Revision ID: 26567dca90fa
Revises: 447f8c701f41
Create Date: 2023-01-13 00:29:19.036543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26567dca90fa'
down_revision = '447f8c701f41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
