"""id type replace integer to uuid

Revision ID: 447f8c701f41
Revises: 95c520d4e900
Create Date: 2023-01-12 18:38:04.474432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447f8c701f41'
down_revision = '95c520d4e900'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
