"""track model fix2

Revision ID: 9f659034d50c
Revises: ebe12dd4c195
Create Date: 2023-01-12 18:15:41.548235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f659034d50c'
down_revision = 'ebe12dd4c195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('attraction_id', sa.Integer(), nullable=False))
    op.add_column('places', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.drop_constraint('places_attractions_id_fkey', 'places', type_='foreignkey')
    op.drop_constraint('places_restaurants_id_fkey', 'places', type_='foreignkey')
    op.create_foreign_key(None, 'places', 'restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key(None, 'places', 'attractions', ['attraction_id'], ['id'])
    op.drop_column('places', 'attractions_id')
    op.drop_column('places', 'restaurants_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('restaurants_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('places', sa.Column('attractions_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.create_foreign_key('places_restaurants_id_fkey', 'places', 'restaurants', ['restaurants_id'], ['id'])
    op.create_foreign_key('places_attractions_id_fkey', 'places', 'attractions', ['attractions_id'], ['id'])
    op.drop_column('places', 'restaurant_id')
    op.drop_column('places', 'attraction_id')
    # ### end Alembic commands ###
