"""track model fix

Revision ID: ebe12dd4c195
Revises: ee752ef23d75
Create Date: 2023-01-12 18:10:21.626459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe12dd4c195'
down_revision = 'ee752ef23d75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
