"""refactoring model user expresion

Revision ID: ee752ef23d75
Revises: f04090b0b11a
Create Date: 2023-01-12 17:59:18.476867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee752ef23d75'
down_revision = 'f04090b0b11a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_travel_experiences', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_travel_experiences', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_travel_experiences', type_='foreignkey')
    op.drop_column('user_travel_experiences', 'city_id')
    # ### end Alembic commands ###
