"""add new apps adonates and dreams

Revision ID: 8321d984b6b4
Revises: 26567dca90fa
Create Date: 2023-01-14 01:05:22.352806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8321d984b6b4'
down_revision = '26567dca90fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
